language: node_js

node_js:
  - 20

install:
  - yarn install

jobs:
  include:
    - stage: Unit Tests + Coverage
      script: yarn test:coverage
    - stage: Dependency Audit
      script: yarn test:audit
